name: Pull Request
on:
  pull_request:
    branches:
      - '*'

  workflow_dispatch:

jobs:
  test:
    name: Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 'lts/*'

      - name: Install Dependencies
        run: npm ci

      - name: Tests
        run: npm run test:ci
